{% set version = "4.0.0" %}

package:
  name: python-clang
  version: {{ version }}

source:
  url: http://llvm.org/releases/{{ version }}/cfe-{{ version }}.src.tar.xz
  sha256: cea5f88ebddb30e296ca89130c83b9d46c2d833685e2912303c828054c4dc98a

build:
  number: 0
  noarch: python
  script:
    - mkdir -p "${SP_DIR}"
    - cp -r bindings/python/clang "${SP_DIR}"

requirements:
  host:
    - python =2
  run:
    - python =2
    - clang =={{ version }}

test:
  requires:
    - nose
  source_files:
    - bindings/python/tests
    - bindings/python/examples/cindex
  imports:
    - clang
    - clang.cindex
  commands:
    - cd bindings/python
    - cp tests/cindex/util.py tests
    - nosetests -v

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: Python bindings for clang

extra:
  recipe-maintainers:
    - chrisburr
